build:
    environment:
        mongodb: '2.6'
    project_setup:
        before:
            - mongo test --eval "db.createUser({ user:'liquidbox', pwd:'liquidbox', roles:[ 'readWrite' ] }); db.createUser({ user:'ro_user', pwd:'p%:@/?=&', roles:[ 'read' ] });"
    tests:
        override:
            -
                command: vendor/bin/phpunit --coverage-clover=coverage.xml
                coverage:
                    file: coverage.xml
                    format: clover
    nodes:
        'PHP 5.6':
            environment:
                php: '5.6'
filter:
    excluded_paths:
        - tests/
checks:
    php:
        code_rating: true
        duplication: true
tools:
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
    php_code_coverage: true
